### PR TITLE
Fix Issue #14

### LINKED ISSUE #14: Entering an invalid breed for /dog causes the bot to error
Pretty much what the title says, running `/dog <breed-that-doesn't-exist>` results in the bot sending "Ive has experienced an internal error". The error logged to the console is: `DiscordRESTError [50035]: Invalid Form Bodyembed.image.url: Not a well formed URL.`

### PR DESCRIPTION
**Pull request by xVyre**
Fix #14 
This was due to the API changing their 404 message. I also made it try joining the arguments if a sub breed isn't found, so that doing `/dog german shepherd` is possible

### CODE REVIEW

File: server/bot/commands/api.ts [hunk 1]
```diff
@@ -224,10 +224,22 @@ export const handleDog: Command = {
...
+          )).json())
+          if (!(message.includes('Beed not found'))) {
+            return {
+              embed: { image: { url: message }, color: 0x654321 },
+              content: `🐕 ${args.join('')}`
+            }
+          } else {
+            return 'This breed/sub-breed does not exist!'
+          }
+        }
```
Comment (retrixe) [inline server/bot/commands/api.ts:242]: There are no dogs with spaces, it should always be joined.
```suggestion
        if (!message || message.includes('Breed not found')) return 'This breed/sub-breed does not exist!'
```

File: server/bot/commands/api.ts [hunk 2]
```diff
@@ -224,10 +224,22 @@ export const handleDog: Command = {
       // Fetch a random picture for a sub-breed.
     } else if (args[0] && args[1]) {
       try {
-        const { message } = await (await fetch(
+        let { message } = await (await fetch(
           `http://dog.ceo/api/breed/${args[0].toLowerCase()}/${args[1].toLowerCase()}/images/random`
```
Comment (retrixe) [inline server/bot/commands/api.ts:228]: There are no dogs with spaces, it should always be joined.
```suggestion
        const { message } = await (await fetch(
          `http://dog.ceo/api/breed/${args.join('').toLowerCase()}/${args[1].toLowerCase()}/images/random`
```

File: server/bot/commands/api.ts [hunk 3]
```diff
@@ -224,10 +224,22 @@ export const handleDog: Command = {
...
         )).json()
-        if (!message || message === 'Breed not found') return 'This breed/sub-breed does not exist!'
+        if (!message || message.includes('Breed not found')) {
+          ({ message } = await (await fetch(
+            `http://dog.ceo/api/breed/${args.join('').toLowerCase()}/images/random`
+          )).json())
+          if (!(message.includes('Beed not found'))) {
```
Comment (retrixe) [inline server/bot/commands/api.ts:234]: `Breed*` not `Beed`.
```suggestion
          if (!(message.includes('Breed not found'))) {
```

**Review by retrixe — CHANGES_REQUESTED** [review]
No dogs have spaces in their name, the arguments should always be joined, the only positive of doing it like this is that invalid commands like `/dog shiba literally anything here` works, but also incur a performance cost even valid usages.

File: server/bot/commands/api.ts [hunk 4]
```diff
@@ -227,7 +227,7 @@ export const handleDog: Command = {
         const { message } = await (await fetch(
           `http://dog.ceo/api/breed/${args[0].toLowerCase()}/${args[1].toLowerCase()}/images/random`
         )).json()
-        if (!message || message === 'Breed not found') return 'This breed/sub-breed does not exist!'
+        if (!message || message.includes('Breed not found')) return 'This breed/sub-breed does not exist!'
```
Comment (retrixe) [inline server/bot/commands/api.ts:230]:
```suggestion
        if (message.includes('Breed not found')) {
          ({ message } = await (await fetch(
            `http://dog.ceo/api/breed/${args.join('').toLowerCase()}/images/random`
          )).json())
        }
        if (!message || message.includes('Breed not found')) return 'This breed/sub-breed does not exist!'
```

File: server/bot/commands/api.ts [hunk 5]
```diff
@@ -227,7 +227,7 @@ export const handleDog: Command = {
         const { message } = await (await fetch(
```
Comment (retrixe) [inline server/bot/commands/api.ts:227]:
```suggestion
        let { message } = await (await fetch(
```

**Review by retrixe — APPROVED** [review]
Well, the previous suggestions were pretty bad since I failed to notice there are sub-breeds, but this is a better iteration of those changes that have been reverted now, I suppose this is fine.

**Review by retrixe — APPROVED** [review]
